import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MoonField",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       <html lang="en">
      <body className={inter.className}>
   
          <div className="relative w-full">
            <Navbar />
          </div>
          {children}
          <div className="relative footer w-full">
            <Footer />
          </div>
    
      </body>
    </html>
    </html>
  );
}
